name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:

    name: Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Installing Dependencies
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - name: Build
      run: cargo build --all-targets
  
  build-macos:

    name: MacOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      run: cargo build --all-targets
  
  build-windows:

    name: Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      run: cargo build --all-targets
